<?php

$en_path = __DIR__ . '/lang/en.json';
$en = json_decode(file_get_contents($en_path), true);

$translations = [
    "Nouvel événement" => "New event",
    "Titre" => "Title",
    "Ex: Soirée jeux de société" => "Ex: Board game night",
    "Date et heure" => "Date and time",
    "Lieu" => "Location",
    "Ex: Local 1234 or Discord" => "Ex: Room 1234 or Discord",
    "Participants max (optionnel)" => "Max participants (optional)",
    "Illimité si vide" => "Unlimited if empty",
    "Description" => "Description",
    "Détails sur l\\'activité..." => "Activity details...",
    "Publier l\\'événement" => "Publish event",
    "Supprimer cet événement ?" => "Delete this event?",
    "Organisateur" => "Organizer",
    "Illimité" => "Unlimited",
    "Quitter" => "Leave",
    "Complet" => "Full",
    "Rejoindre" => "Join",
    "Aucun intérêt listé" => "No listed interests",
    "En attente" => "Pending",
    "Répondre" => "Reply",
    "Signaler un utilisateur" => "Report a user",
    "Veuillez préciser la raison de ce signalement. Nous traiterons cette demande avec attention." => "Please specify the reason for this report. We will process this request carefully.",
    "Expliquez brièvement..." => "Explain briefly...",
    "Envoyer" => "Send",
    "URL de l\\'image :" => "Image URL:",
    "Bloquer cet utilisateur" => "Block this user",
    "Êtes-vous sûr de vouloir bloquer cet utilisateur ? Vous ne verrez plus ses publications et il ne pourra plus interagir avec vous." => "Are you sure you want to block this user? You will no longer see their posts and they will no longer be able to interact with you.",
    "Signaler ce contenu" => "Report this content",
    "Événements" => "Events",
    "Administrateur" => "Administrator",
    "Panel Admin" => "Admin Panel",
    "S’inscrire — Pulse" => "Register — Pulse",
    "Connexion — Pulse" => "Login — Pulse",
    "Téléphone (Optionnel)" => "Phone (Optional)",
    "Sécurité du compte" => "Account Security",
    "Question de secours" => "Security Question",
    "Réponse" => "Answer",
    "Réinitialisation — Pulse" => "Reset — Pulse",
    "Pas de soucis. Indiquez votre adresse courriel pour recevoir un lien, ou utilisez votre question de secours." => "No worries. Enter your email address to receive a link, or use your security question.",
    "Courriel institutionnel" => "Institutional email",
    "Envoyer le lien" => "Send link",
    "Utiliser ma question de secours" => "Use my security question",
    "Retour à la connexion" => "Back to login",
    "Réinitialiser le mot de passe" => "Reset Password",
    "Réinitialisation Sécurisée — Pulse" => "Secure Reset — Pulse",
    "Entrez votre courriel pour retrouver votre question de secours." => "Enter your email to retrieve your security question.",
    "Recherche..." => "Searching...",
    "Trouver ma question" => "Find my question",
    "Votre question" => "Your question",
    "Votre réponse" => "Your answer",
    "Retour" => "Back",
    "Vérification — Pulse" => "Verification — Pulse",
    "Vérifiez votre compte." => "Verify your account.",
    "Nous avons envoyé un code de validation à votre adresse @edu.cegeptr.qc.ca. Veuillez le saisir ci-dessous." => "We have sent a validation code to your @edu.cegeptr.qc.ca address. Please enter it below.",
    "Un nouveau code a été envoyé." => "A new code has been sent.",
    "Code de validation" => "Validation code",
    "Vérifier" => "Verify",
    "Renvoyer le code" => "Resend code",
    "Message" => "Message",
    "Tableau de bord" => "Dashboard",
    "Chercher par nom ou intérêt (ex: Gaming, Arts...)" => "Search by name or interest (ex: Gaming, Arts...)",
    "Aucun résultat" => "No results",
    "Essayez avec d\\'autres mots clés." => "Try with other keywords.",
    "Connexions" => "Connections",
    "Mentions J\\'aime" => "Likes",
    "Publications" => "Posts",
    "TOTAL" => "TOTAL",
    "Commentaires" => "Comments",
    "Intérêts" => "Interests",
    "Demandes" => "Requests",
    "Activités récentes" => "Recent activities",
    "a aimé votre post" => "liked your post",
    "a commenté votre post" => "commented on your post",
    "Aucune activité." => "No activity.",
    "Activités" => "Activities",
    "Créer un événement" => "Create an event",
    "Aucun événement prévu" => "No upcoming events",
    "Soyez le premier à organiser une activité sur Pulse !" => "Be the first to organize an activity on Pulse!",
    "Bienvenue dans l\\'espace" => "Welcome to the space",
    "Prêt à élargir ton réseau aujourd\\'hui ?" => "Ready to expand your network today?",
    "Trouve des partenaires d\\'étude passionnés et booste tes résultats." => "Find passionate study partners and boost your results.",
    "Profil — Pulse" => "Profile — Pulse",
    "Étudiant.e Pulse" => "Pulse Student",
    "Paramètres" => "Settings",
    "Identité & Bio" => "Identity & Bio",
    "Nom, programme, photo, intérêts" => "Name, program, photo, interests",
    "Mot de passe et accès au compte" => "Password and account access",
    "Compte" => "Account",
    "Supprimer définitivement votre compte" => "Permanently delete your account",
    "Sports" => "Sports",
    "Jeux" => "Games",
    "Gaming" => "Gaming",
    "Autres" => "Others",
    "Débloquer l\\'utilisateur" => "Unblock user",
    "Bloquer l\\'utilisateur" => "Block user",
    "Êtes-vous sûr de vouloir débloquer cet utilisateur ? Il pourra à nouveau voir votre profil et interagir avec vous." => "Are you sure you want to unblock this user? They will be able to see your profile and interact with you again.",
    "En bloquant cet utilisateur, il ne pourra plus voir votre profil, vos publications ou vous envoyer de messages." => "By blocking this user, they will no longer be able to see your profile, your posts, or send you messages.",
    "Signaler cet utilisateur" => "Report this user"
];

foreach ($translations as $key => $val) {
    if (isset($en[$key])) {
        $en[$key] = $val;
    }
}

file_put_contents($en_path, json_encode($en, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

echo "Translated.\n";
